version = 0.1

[dev.deploy.parameters]
stack_name = "SimpleBlueTimeline"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "EnvironmentName=dev",
    "LogLevel=DEBUG",
    "TimelineName=MyTimeline"
]

[integration-testing.deploy.parameters]
region = "eu-west-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "EnvironmentName={{TESTING_ENV_NAME}}",
    "LogLevel=DEBUG",
    "TimelineName=TestTimeline"
]
